// File: app.http

// Define a variable for your base URL
@baseUrl = http://localhost:3000/api/v1

###
# @name registerUser
# Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "full_name": "Johns Mwangi",
  "email": "johnsonthuraniramwangi@gmail.com",
  "password": "@johnson2001mwangi"
 
  
}

###
# @name loginUser
# Login to get JWT tokens
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "johnsonthuraniramwangi@gmail.com",
  "password": "@johnson2001mwangi"

}

###
# @name getMyProfile
# Get the profile of the logged-in user (requires auth)
# NOTE: You need to replace "YOUR_ACCESS_TOKEN" with the one from the login response.
GET {{baseUrl}}/users
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiam9obnNvbnRodXJhbmlyYW13YW5naUBnbWFpbC5jb20iLCJzY2hvb2xfaWQiOm51bGwsInJvbGVzIjpbeyJyb2xlIjoic3VwZXJfYWRtaW4ifV0sImlhdCI6MTc1MDM0MzY4OSwiZXhwIjoxNzUwMzQ0NTg5fQ.Dd4t9Ndaj8EnJ_mQXSU_0JHmjsD6iXWr18mwKv2AVQM"
###
# @name requestPasswordReset
# Request a password reset link
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "john.doe@example.com"
}


###
# @name healthCheck
# Check the health of the application
GET {{baseUrl}}/health


//creating a   school
#### @name createSchool
# Create a new school (requires auth)
POST {{baseUrl}}/schools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiam9obnNvbnRodXJhbmlyYW13YW5naUBnbWFpbC5jb20iLCJzY2hvb2xfaWQiOm51bGwsInJvbGVzIjpbeyJyb2xlIjoic3VwZXJfYWRtaW4ifV0sImlhdCI6MTc1MDM0MzY4OSwiZXhwIjoxNzUwMzQ0NTg5fQ.Dd4t9Ndaj8EnJ_mQXSU_0JHmjsD6iXWr18mwKv2AVQM
Content-Type: application/json

{
    "name": "Serene Valley International School",
    "address": "123 Education Lane, Nairobi, Kenya",
    "contact_phone": "+254712345678",
    "contact_email": "admissions@serenevalley.ac.ke",
    "school_logo_url": "https://example.com/logos/serene_valley_logo.png"
}

###
//super admin creating  a  school admin 
#### @name createSchoolAdmin
# Create a new school admin (requires auth)
POST {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiam9obnNvbnRodXJhbmlyYW13YW5naUBnbWFpbC5jb20iLCJzY2hvb2xfaWQiOm51bGwsInJvbGVzIjpbeyJyb2xlIjoic3VwZXJfYWRtaW4ifV0sImlhdCI6MTc1MDM0MzY4OSwiZXhwIjoxNzUwMzQ0NTg5fQ.Dd4t9Ndaj8EnJ_mQXSU_0JHmjsD6iXWr18mwKv2AVQM
Content-Type: application/json

{
    "full_name": "Dr. Jane Doe",
    "email": "principal@serenevalley.ac.ke",
    "password": "strongpassword123",
    "phone_number": "0700111222",
    "school_id": 1,
    "roles": [
        "school_admin"
    ]
}
