import { Module } from '@nestjs/common';
import { DrizzleModule } from '../../drizzle/drizzle.module';
import { PlatformInvoicesController } from './platform-invoices.controller';
import { PlatformInvoicesService } from './platform-invoices.service';
import { SubscriptionsModule } from '../subscriptions/subscriptions.module';

/**
 * Manages invoices generated by the platform for school subscriptions.
 */
@Module({
  imports: [
    DrizzleModule,
    SubscriptionsModule, // Provides SubscriptionsService
  ],
  controllers: [PlatformInvoicesController],
  providers: [PlatformInvoicesService],
  exports: [PlatformInvoicesService], // Export for use by PlatformPaymentsModule
})
export class PlatformInvoicesModule {}
